receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  file:
    path: /var/lib/oltp/traces.jsonl

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
