

# INSERT
DEBUG=TRUE INSERT_BALANCE_STRATEGY=NO_BALANCE RESULT_PATH=. TRACING=FALSE INSERT_BATCH_SIZE=1 INSERT_DATA_FILEPATH=../../utils/random.npy INSERT_CORPUS_SIZE=100 INSERT_CLIENTS_PER_PROXY=1 ACTIVE_TASK=INSERT TASK=QUERY NUM_PROXIES=1 go run .

# QUERY
DEBUG=TRUE QUERY_BALANCE_STRATEGY=NO_BALANCE RESULT_PATH=. TRACING=FALSE QUERY_BATCH_SIZE=1 QUERY_DATA_FILEPATH=../../utils/random.npy QUERY_CORPUS_SIZE=100 QUERY_CLIENTS_PER_PROXY=1 ACTIVE_TASK=QUERY TASK=QUERY NUM_PROXIES=1 go run .
